# -*- coding: utf-8 -*-
"""Q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4Xccf3BFK9FCNExjAQDuXvQWrMkXV44
"""

def freq(str):
    words = str.lower().split()
    word_ct = {}

    for word in words:
      word_ct[word] = word_ct.get(word,0) + 1
    sorted_words = dict(sorted(word_ct.items()))
    return sorted_words
str = 'Students to appear for the test, all students are required to fill the test form for betterment'
str = str.replace(",", "")

for word, count in freq(str).items():
    print(f'{word}: {count}')