# -*- coding: utf-8 -*-
"""Q11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dv9_P4Akzcu6Ljti_5LvmtIbj2WrzNiT
"""

l1 = [1,2,3,5,6,7]
l2 = [2,3,4,7,8,5,10]

def create_list(l1,l2):
  l3 = []
  for item in l1 and l2:
    if item in l1 and l2:
      l3.append(item)
  print(l3)

create_list(l1,l2)