# -*- coding: utf-8 -*-
"""Q12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEU_0HxZcLirqbPlZsgQEPETK9O8Zrkg
"""

def prime_fact(n, div=2):
    if n == 1:
        return []

    if n % div == 0:
        return [div] + prime_fact(n // div, div)
    return prime_fact(n, div + 1)

no = int(input("Enter a positive int: "))
factors = prime_fact(no)
print(f"Prime factors of {no}: {factors}")