# -*- coding: utf-8 -*-
"""Q13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elQRjWLShKluS49hYqYZNlNaQhvlz8E8
"""

def bin_eq(n):
  if n==0:
    return ''
  return bin_eq(n//2) + str(n%2)

num = int(input('enter num: '))
binary = bin_eq(num)
print(f'binary eq of {num} is: {binary}')