# -*- coding: utf-8 -*-
"""Q14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicuDowGrAeFWvffrjPXE-3lviqgCJue
"""

str = input('enter a string: ')
def vow_ct(str):
  count = sum(1 for i in str.lower() if i in 'aeiou')
  return count

print('number of vowels in the string are: ',vow_ct(str))