# -*- coding: utf-8 -*-
"""Q16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdXHPdHfn_dvUqA1YGalXTU3XveXT6JB
"""

def power(a, b):
  if b==0:
    return 1
  return a * power(a, b-1)

a = int(input('enter base a: '))
b = int(input('enter power b: '))
result = power(a, b)
print(f"{a} raised to the power {b} is: {result}")