# -*- coding: utf-8 -*-
"""Q1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_r9D1E2IqLbFRDsOGEIaPyvh9W5IMNdh
"""

def count_case(str):
    upper_ct = 0
    lower_ct = 0

    for char in str:
        if char.isupper():
            upper_ct += 1
        elif char.islower():
            lower_ct += 1

    return upper_ct, lower_ct

str = input("Enter a string: ")
upper, lower = count_case(str)
print(f"Number of uppercase letters: {upper}")
print(f"Number of lowercase letters: {lower}")



