# -*- coding: utf-8 -*-
"""Q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJYM-X-RaLn5rt4RtN-Sr_OlKge6HCNR
"""

def avg_sum(m1,m2,m3,m4,m5):
  tot = m1+m2+m3+m4+m5
  avg = tot/5
  return tot, avg

tot, avg = avg_sum(110,40,44,50,16)
print('total:', tot)
print('average:', avg)