# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101ZdlklGKeH4DE6PtHtON685h8mp6z_1
"""

def create_tuple(n):
  result = [(x,x**2,x**3) for x in range(1,n+1)]
  return result
n = int(input('n = '))
result_list = create_tuple(n)
print(result_list)

