# -*- coding: utf-8 -*-
"""Q8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VWZGagRrA2VTd6TcR_OlzXn6foRFJY-
"""

def convert(sent):
   words = sent.split()
   sort_words = sorted(set(words))
   return " ".join(sort_words)

sent = 'i like banana orange apple orange not much but apple is good'
print(convert(sent))