# -*- coding: utf-8 -*-
"""Q9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTha7dtoutRN_IwZ_9KgGCKeqwiDMHT6
"""

def ct_alpha_digits(str):
  ct_alpha = 0
  ct_digit = 0
  for item in str:
    if item.isalpha():
      ct_alpha += 1
    elif item.isdigit():
      ct_digit += 1
  return ct_alpha, ct_digit

str = input("string: ")
ct_alpha, ct_digit = ct_alpha_digits(str)
print("Number of alphabets: ", ct_alpha)
print("Number of digits: ", ct_digit)